// Builds an atomic first installation for SQL Editor. Does not connect remotely.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
const folder = 'supabase/migrations';
const files = readdirSync(folder).filter(f => /^\d+_.+\.sql$/.test(f)).sort();
const chunks = files.map(file => ({ file, sql: readFileSync(`${folder}/${file}`, 'utf8') }));
const seed = readFileSync('supabase/generated/entity_identities.sql', 'utf8');
const receipt = chunks.map(({file,sql}) => {
  const [version, ...name] = file.replace(/\.sql$/, '').split('_');
  return {version, name:name.join('_'), sha256:createHash('sha256').update(sql).digest('hex')};
});
const sql = `-- Generated by scripts/export_supabase_bootstrap.mjs. Do not edit.
-- FIRST INSTALL ONLY. No user/owner grant is included.
-- Run the WHOLE file in SQL Editor as postgres, not a selected fragment.
-- If any statement fails, ROLLBACK; stop and inspect. Never skip the guard.
-- SQL Editor does not update Supabase CLI history: follow LUNA_DEPLOY_TALIMATLARI.md.
begin;
set local lock_timeout = '10s';
set local statement_timeout = '120s';
do $guard$
begin
  if to_regclass('public.world_entity_identities') is not null
    or to_regclass('public.wiki_articles') is not null
    or to_regtype('public.editor_role') is not null then
    raise exception 'Ejder schema already exists. Do not rerun bootstrap; inspect migration history.';
  end if;
end;
$guard$;
${chunks.map(({file,sql}) => `\n-- SOURCE: ${file}\n${sql}`).join('\n')}
-- SOURCE: generated/entity_identities.sql (transaction wrapper removed)
${seed.replace(/^begin;\s*$/m,'').replace(/^commit;\s*$/m,'')}
create table private.bootstrap_receipts (
  version text primary key,
  name text not null,
  sha256 text not null,
  installed_at timestamptz not null default now()
);
revoke all on private.bootstrap_receipts from public, anon, authenticated;
insert into private.bootstrap_receipts(version,name,sha256) values
${receipt.map(r=>`('${r.version}','${r.name}','${r.sha256}')`).join(',\n')};
notify pgrst, 'reload schema';
commit;
select 'Ejder kurulumu tamamlandı; owner ataması ayrı adımdır.' as sonuc,
  count(*) as kimlik_sayisi, count(*) filter (where active) as etkin_kimlik_sayisi
from public.world_entity_identities;
`;
writeFileSync('supabase/generated/bootstrap_editorial.sql', sql);
writeFileSync('supabase/generated/bootstrap_manifest.json', JSON.stringify({purpose:'first-install-sql-editor',migrations:receipt,seed_sha256:createHash('sha256').update(seed).digest('hex')},null,2)+'\n');
console.log(`Prepared ${files.length} migrations + identity seed; no remote changes.`);
